---
name: default
author: Edward Wang <@WangEdward>
supported_llms:
  - all
init:
  - action: system/use-tts-engine
    args:
      engine: null
      voice: null
input:
  - action: system/text
    args:
      text: ${{ input.message }}
    output: input.message
output:
  - action: system/text
    name: send_message
    args:
      text: ${{ output.message }}
  - action: tts/speak
    when: tts_engine
    name: tts_speak
    args:
      text: ${{ output.message }}
  - action: system/user_message
    when: tts_speak
    args:
      voice: tts_speak
