---
name: default
author: Edward Wang <@WangEdward>
supported_llms:
  # please also add new llms here
  - chatgpt-api
  - chatglm-api
  - chatgpt-web
  - poe-claude
  - poe-chatgpt
  - slack-claude
  - bing-c
  - bing-p
  - bing-b
  - bard
  - yiyan
input:
  - action: system/text
    args:
      text: ${{ input.message }}
    output: input.message
output:
  - action: system/text
    name: send_message
    args:
      text: ${{ output.message }}
