---
name: default
author: Edward Wang <@WangEdward>
supported_llms:
  - all
input:
  - action: system/text
    args:
      text: ${{ input.message }}
    output: input.message
output:
  - action: system/text
    name: send_message
    args:
      text: ${{ output.message }}
