version: '3.4'
services:
  chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:browser-version
    restart: always
    environment:
      LANG: 'C.UTF-8'
      XPRA_PASSWORD: 'lss233' # XPRA 密码，建议修改
    volumes:
      - ./config.cfg:/app/config.cfg
      - ./data:/app/data
      - ./presets:/app/presets # 如果你想自定义预设，就解除注释
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
  watchtower: # [可选] 自动更新
    image: containrrr/watchtower
    volumes: # 如果启动失败，请修改下面这条：
      - /var/run/docker.sock:/var/run/docker.sock
