name: Create Quickstart for Windows 64

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Quickstart
    runs-on: Windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate files
      run: |
        mkdir C:/generated_files
        mkdir C:/tmp_files
        echo "Creating folders..."
        cd C:/generated_files
        mkdir mirai
        mkdir chatgpt
        echo "Downloading mcl-installer ..."
        Invoke-WebRequest -URI https://github.com/iTXTech/mcl-installer/releases/download/a02f711/mcl-installer-a02f711-windows-amd64.exe -OutFile C:/generated_files/mirai/mcl-installer.exe
    - name: Copy files
      run: |
        cp -r D:\a\chatgpt-mirai-qq-bot\chatgpt-mirai-qq-bot\* C:\generated_files\chatgpt\
        echo "Downloading Python3.9 ..."
        Invoke-WebRequest https://www.python.org/ftp/python/3.9.13/python-3.9.13-embed-amd64.zip -OutFile C:/tmp_files/python.zip
        7z x C:/tmp_files/python.zip -r -oC:/generated_files/chatgpt/python3.9

        echo "Downloading get-pip.py ..."
        Invoke-WebRequest -URI https://bootstrap.pypa.io/get-pip.py -OutFile C:/generated_files/chatgpt/python3.9/get-pip.py
        echo "import site" >> C:/generated_files/chatgpt/python3.9/python39._pth

        echo "Moving files..."
        mv D:\a\chatgpt-mirai-qq-bot\chatgpt-mirai-qq-bot\.github\quickstarts\windows\ C:/generated_files/files/

        echo "Replacing..."
        cp C:/generated_files/files/scripts/初始化.cmd C:/generated_files/
        
        Invoke-WebRequest -URI https://github.com/lss233/awesome-chatgpt-qq-presets/archive/refs/heads/master.zip -OutFile C:/tmp_files/presets.zip
        7z x C:/tmp_files/presets.zip -oC:/tmp_files/
        cp -rf C:/tmp_files/awesome-chatgpt-qq-presets-master/* C:/generated_files/chatgpt/presets/
        
        Invoke-WebRequest -URI https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.mxe-cross-win64.7z -O C:/tmp_files/wkhtmltox.7z
        
        echo "Packing..."
        7z a quickstart-windows-amd64.zip
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          quickstart-windows-amd64.zip
    - name: Upload compressed files to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: quickstart-windows-amd64.zip
        asset_name: Windows-quickstart-${{ github.ref }}.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "quickstart-windows-amd64.zip 是为 Windows x64 用户准备的快速启动包"
        
